apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: weatherapp-frontend
  name: weatherapp-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weatherapp-frontend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: weatherapp-frontend
    spec:
      containers:
      - image: gcr.io/weatherapp-370511/weatherapp-frontend:v1
        name: frontend
        imagePullPolicy: Always
        resources: {}
        ports:
          - containerPort: 8000 
status: {}
